# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4638ee4e3230ab3dce5280fe6c78e6bcb7d3fb924ae6f4f69b310a5c5ff1a2f7047cefc6560e78aeef83e2e051591d1b2948863d45c5633ef63e515ea9a6217

test:
  secret_key_base: f278a7d61a6be5adea482e042f067b8b89a299b0f177b9e1a3af307891e5066ea6cbfac4e447fbeb13db1fb3f26343261203864faefe00476d8dd9552051e03b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
